import React from 'react';
import axios from 'axios';
import { GENRE_ENDPOINT, GET_ACCESS_TOKEN } from '../lib/spotify';
import Head from 'next/head';

const Genre = ({ genre }) => {
  return (
    <div>
      <Head>
        <title>Spotify Recommender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>{genre}</main>

      <footer></footer>
    </div>
  );
};

export default Genre;

export async function getStaticPaths() {
  let token = await GET_ACCESS_TOKEN();
  let genres = await axios(GENRE_ENDPOINT, {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  }).then((res) => res.data.genres);

  const genrePaths = genres.map((genre) => {
    return { params: { genre } };
  });

  return {
    paths: genrePaths,
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  return {
    props: { genre: params.genre },
  };
}
