import Head from 'next/head';
import Image from 'next/image';
import '../styles/Home.module.scss';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Spotify Recommender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>

      <footer></footer>
    </div>
  );
}
