import Head from 'next/head';
import Image from 'next/image';
import '../styles/Home.module.scss';
import {
  TOKEN,
  GENRE_ENDPOINT,
  getAccessToken,
  TOKEN_ENDPOINT,
  basic,
} from '../lib/spotify';

export default function Home({ genres }) {
  return (
    <div>
      <Head>
        <title>Spotify Recommender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>

      <footer></footer>
    </div>
  );
}

export async function getStaticProps() {
  const token = await fetch(TOKEN_ENDPOINT, {
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      Authorization: `Basic ${basic}`,
    },
    data: 'grant_type=client_credentials',
    method: 'POST',
  }).then((response) => response.json());
  console.log(token);
  // console.log(getAccessToken());
  const genres = await fetch(GENRE_ENDPOINT, {
    method: 'GET',
    headers: {
      Authorization: `Bearer ${token}`,
    },
  }).then((response) => response.json());

  return {
    props: { genres },
  };
}
