import axios from 'axios';
import Head from 'next/head';
import Image from 'next/image';
import '../styles/Home.module.scss';
import { GENRE_ENDPOINT, getAccessToken } from '../lib/spotify';

export default function Home({ genres }) {
  console.log(genres);
  return (
    <div>
      <Head>
        <title>Spotify Recommender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>

      <footer></footer>
    </div>
  );
}

export async function getStaticProps() {
  const token = await getAccessToken();
  const genres = await axios(GENRE_ENDPOINT, {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  }).then((res) => res.data.genres);

  return {
    props: { genres },
  };
}
